---
- hosts: all
  remote_user: cilab
  become: yes
  become_method: sudo
  become_user: root

  vars_files:
    - "../vault/passwords.yaml"

  vars:
    ansible_become_pass: "{{ admin_password }}"

  tasks:
    - name: "Remove user '{{ item }}'"
      user:
        name: "{{ item }}"
        state: absent
        remove: yes
      loop:
        - sunlightjh194
        - super_moon
