---
- name: Do the basic set-up (Utils, Nvidia Driver, User Management, Docker)
  hosts: masters
  remote_user: cilab
  become: yes
  become_method: sudo
  become_user: root

  vars_files:
    - "vault/passwords.yaml"

  vars:
    ansible_become_pass: "{{ admin_password }}"
    distribution: "ubuntu18.04"

  tasks:
    - name: "pnging"
      ping: 

  roles:
    #- utils
    #- install-driver
    #- docker-and-driver
    - role: setup-docker
      vars:
        disrtibution: "{{ distribution }}"
    #- role: add-user
    #vars:
    #password: "{{default_password}}"
      
