---
- name: Do the basic set-up (Utils, Nvidia Driver, User Management, Docker)
  hosts: all
  remote_user: cilab
  become: yes
  become_method: sudo
  become_user: root

  vars_files:
    - "vault/passwords.yaml"

  vars:
    ansible_become_pass: "{{ admin_password }}"

  tasks:
    - name: "pnging"
      ping: 

  roles:
    - setup-docker
      #- utils
      #- docker-and-driver
      #- add-user
